// Code generated by MockGen. DO NOT EDIT.
// Source: govatars/internal/delivery/http (interfaces: AvatarQueries)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/http_avatar_mocks.go -package=mocks . AvatarQueries
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "govatars/internal/models"
	usecase "govatars/internal/usecase"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarQueries is a mock of AvatarQueries interface.
type MockAvatarQueries struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarQueriesMockRecorder
	isgomock struct{}
}

// MockAvatarQueriesMockRecorder is the mock recorder for MockAvatarQueries.
type MockAvatarQueriesMockRecorder struct {
	mock *MockAvatarQueries
}

// NewMockAvatarQueries creates a new mock instance.
func NewMockAvatarQueries(ctrl *gomock.Controller) *MockAvatarQueries {
	mock := &MockAvatarQueries{ctrl: ctrl}
	mock.recorder = &MockAvatarQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarQueries) EXPECT() *MockAvatarQueriesMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockAvatarQueries) ByID(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockAvatarQueriesMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockAvatarQueries)(nil).ByID), ctx, id)
}

// DeleteByID mocks base method.
func (m *MockAvatarQueries) DeleteByID(ctx context.Context, actorUserID string, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, actorUserID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockAvatarQueriesMockRecorder) DeleteByID(ctx, actorUserID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockAvatarQueries)(nil).DeleteByID), ctx, actorUserID, id)
}

// DeleteLatestForUser mocks base method.
func (m *MockAvatarQueries) DeleteLatestForUser(ctx context.Context, actorUserID, pathUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLatestForUser", ctx, actorUserID, pathUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLatestForUser indicates an expected call of DeleteLatestForUser.
func (mr *MockAvatarQueriesMockRecorder) DeleteLatestForUser(ctx, actorUserID, pathUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLatestForUser", reflect.TypeOf((*MockAvatarQueries)(nil).DeleteLatestForUser), ctx, actorUserID, pathUserID)
}

// GetImage mocks base method.
func (m *MockAvatarQueries) GetImage(ctx context.Context, id uuid.UUID, size, format string) (*usecase.ImagePayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id, size, format)
	ret0, _ := ret[0].(*usecase.ImagePayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockAvatarQueriesMockRecorder) GetImage(ctx, id, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockAvatarQueries)(nil).GetImage), ctx, id, size, format)
}

// GetLatestImageForUser mocks base method.
func (m *MockAvatarQueries) GetLatestImageForUser(ctx context.Context, userID, size, format string) (*usecase.ImagePayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestImageForUser", ctx, userID, size, format)
	ret0, _ := ret[0].(*usecase.ImagePayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestImageForUser indicates an expected call of GetLatestImageForUser.
func (mr *MockAvatarQueriesMockRecorder) GetLatestImageForUser(ctx, userID, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestImageForUser", reflect.TypeOf((*MockAvatarQueries)(nil).GetLatestImageForUser), ctx, userID, size, format)
}

// ListByUser mocks base method.
func (m *MockAvatarQueries) ListByUser(ctx context.Context, userID string) ([]models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAvatarQueriesMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAvatarQueries)(nil).ListByUser), ctx, userID)
}

// ThumbnailURL mocks base method.
func (m *MockAvatarQueries) ThumbnailURL(id uuid.UUID, size, format string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ThumbnailURL", id, size, format)
	ret0, _ := ret[0].(string)
	return ret0
}

// ThumbnailURL indicates an expected call of ThumbnailURL.
func (mr *MockAvatarQueriesMockRecorder) ThumbnailURL(id, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThumbnailURL", reflect.TypeOf((*MockAvatarQueries)(nil).ThumbnailURL), id, size, format)
}

// Upload mocks base method.
func (m *MockAvatarQueries) Upload(ctx context.Context, userID, filename string, r io.Reader) (*usecase.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, filename, r)
	ret0, _ := ret[0].(*usecase.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarQueriesMockRecorder) Upload(ctx, userID, filename, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarQueries)(nil).Upload), ctx, userID, filename, r)
}
