apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "govatars.fullname" . }}-{{ .Values.worker.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.worker.name }}
    app.kubernetes.io/version: {{ .Values.app.version | quote }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
      app.kubernetes.io/component: {{ .Values.worker.name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Files.Get "files/config.yaml" | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        app.kubernetes.io/component: {{ .Values.worker.name }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.worker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          {{- with .Values.worker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["./worker"]
          env:
            {{- include "govatars.commonEnv" . | nindent 12 }}
            - name: GOVATARS_OTEL_RESOURCE_SERVICE_NAME
              value: govatars_worker
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "govatars.fullname" . }}-config
