receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    compression: "gzip"
    tls:
      insecure: true  # dev only
  prometheus:
    endpoint: '0.0.0.0:8889'
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]