// Code generated by MockGen. DO NOT EDIT.
// Source: govatars/internal/usecase (interfaces: AvatarRepository,ObjectStorage,EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=../repomocks/repo_gen.go -package=repomocks . AvatarRepository,ObjectStorage,EventPublisher
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	models "govatars/internal/models"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// DeleteHard mocks base method.
func (m *MockAvatarRepository) DeleteHard(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHard indicates an expected call of DeleteHard.
func (mr *MockAvatarRepositoryMockRecorder) DeleteHard(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHard", reflect.TypeOf((*MockAvatarRepository)(nil).DeleteHard), ctx, id)
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// GetByIDIncludingDeleted mocks base method.
func (m *MockAvatarRepository) GetByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDIncludingDeleted", ctx, id)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDIncludingDeleted indicates an expected call of GetByIDIncludingDeleted.
func (mr *MockAvatarRepositoryMockRecorder) GetByIDIncludingDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDIncludingDeleted", reflect.TypeOf((*MockAvatarRepository)(nil).GetByIDIncludingDeleted), ctx, id)
}

// GetLatestByUser mocks base method.
func (m *MockAvatarRepository) GetLatestByUser(ctx context.Context, userID string) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUser", ctx, userID)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUser indicates an expected call of GetLatestByUser.
func (mr *MockAvatarRepositoryMockRecorder) GetLatestByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUser", reflect.TypeOf((*MockAvatarRepository)(nil).GetLatestByUser), ctx, userID)
}

// Insert mocks base method.
func (m *MockAvatarRepository) Insert(ctx context.Context, a *models.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAvatarRepositoryMockRecorder) Insert(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAvatarRepository)(nil).Insert), ctx, a)
}

// ListByUser mocks base method.
func (m *MockAvatarRepository) ListByUser(ctx context.Context, userID string) ([]models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAvatarRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAvatarRepository)(nil).ListByUser), ctx, userID)
}

// RestoreSoftDeleted mocks base method.
func (m *MockAvatarRepository) RestoreSoftDeleted(ctx context.Context, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreSoftDeleted", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreSoftDeleted indicates an expected call of RestoreSoftDeleted.
func (mr *MockAvatarRepositoryMockRecorder) RestoreSoftDeleted(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreSoftDeleted", reflect.TypeOf((*MockAvatarRepository)(nil).RestoreSoftDeleted), ctx, id, userID)
}

// SetProcessingStatus mocks base method.
func (m *MockAvatarRepository) SetProcessingStatus(ctx context.Context, id uuid.UUID, status models.ProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProcessingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProcessingStatus indicates an expected call of SetProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) SetProcessingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).SetProcessingStatus), ctx, id, status)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepositoryMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDelete), ctx, id, userID)
}

// UpdateProcessingResult mocks base method.
func (m *MockAvatarRepository) UpdateProcessingResult(ctx context.Context, id uuid.UUID, width, height int, thumbs map[string]map[string]string, status models.ProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingResult", ctx, id, width, height, thumbs, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingResult indicates an expected call of UpdateProcessingResult.
func (mr *MockAvatarRepositoryMockRecorder) UpdateProcessingResult(ctx, id, width, height, thumbs, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingResult", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateProcessingResult), ctx, id, width, height, thumbs, status)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockObjectStorage) GetObject(ctx context.Context, objectKey string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, objectKey)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageMockRecorder) GetObject(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectStorage)(nil).GetObject), ctx, objectKey)
}

// PutObject mocks base method.
func (m *MockObjectStorage) PutObject(ctx context.Context, objectKey string, r io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, objectKey, r, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageMockRecorder) PutObject(ctx, objectKey, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectStorage)(nil).PutObject), ctx, objectKey, r, size, contentType)
}

// RemoveObject mocks base method.
func (m *MockObjectStorage) RemoveObject(ctx context.Context, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockObjectStorageMockRecorder) RemoveObject(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockObjectStorage)(nil).RemoveObject), ctx, objectKey)
}

// StatObject mocks base method.
func (m *MockObjectStorage) StatObject(ctx context.Context, objectKey string) (int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatObject", ctx, objectKey)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StatObject indicates an expected call of StatObject.
func (mr *MockObjectStorageMockRecorder) StatObject(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatObject", reflect.TypeOf((*MockObjectStorage)(nil).StatObject), ctx, objectKey)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishJSON mocks base method.
func (m *MockEventPublisher) PublishJSON(ctx context.Context, routingKey, messageID string, body any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishJSON", ctx, routingKey, messageID, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishJSON indicates an expected call of PublishJSON.
func (mr *MockEventPublisherMockRecorder) PublishJSON(ctx, routingKey, messageID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishJSON", reflect.TypeOf((*MockEventPublisher)(nil).PublishJSON), ctx, routingKey, messageID, body)
}
