app:
  name: govatars

server:
  name: server
  replicaCount: 1

  image:
    repository: govatars-server
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: ClusterIP
    port: 80

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

worker:
  name: worker
  replicaCount: 1

  image:
    repository: govatars-worker
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: ClusterIP
    port: 80

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
