// Package httphandler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httphandler

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ThumbnailInfoFormat.
const (
	ThumbnailInfoFormatJpeg ThumbnailInfoFormat = "jpeg"
	ThumbnailInfoFormatPng  ThumbnailInfoFormat = "png"
	ThumbnailInfoFormatWebp ThumbnailInfoFormat = "webp"
)

// Valid indicates whether the value is a known member of the ThumbnailInfoFormat enum.
func (e ThumbnailInfoFormat) Valid() bool {
	switch e {
	case ThumbnailInfoFormatJpeg:
		return true
	case ThumbnailInfoFormatPng:
		return true
	case ThumbnailInfoFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	FormatJpeg Format = "jpeg"
	FormatPng  Format = "png"
	FormatWebp Format = "webp"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case FormatJpeg:
		return true
	case FormatPng:
		return true
	case FormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for Size.
const (
	SizeN100x100 Size = "100x100"
	SizeN128x128 Size = "128x128"
	SizeN256x256 Size = "256x256"
	SizeN300x300 Size = "300x300"
	SizeN512x512 Size = "512x512"
	SizeN64x64   Size = "64x64"
	SizeOriginal Size = "original"
)

// Valid indicates whether the value is a known member of the Size enum.
func (e Size) Valid() bool {
	switch e {
	case SizeN100x100:
		return true
	case SizeN128x128:
		return true
	case SizeN256x256:
		return true
	case SizeN300x300:
		return true
	case SizeN512x512:
		return true
	case SizeN64x64:
		return true
	case SizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarImageParamsSize.
const (
	GetAvatarImageParamsSizeN100x100 GetAvatarImageParamsSize = "100x100"
	GetAvatarImageParamsSizeN128x128 GetAvatarImageParamsSize = "128x128"
	GetAvatarImageParamsSizeN256x256 GetAvatarImageParamsSize = "256x256"
	GetAvatarImageParamsSizeN300x300 GetAvatarImageParamsSize = "300x300"
	GetAvatarImageParamsSizeN512x512 GetAvatarImageParamsSize = "512x512"
	GetAvatarImageParamsSizeN64x64   GetAvatarImageParamsSize = "64x64"
	GetAvatarImageParamsSizeOriginal GetAvatarImageParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarImageParamsSize enum.
func (e GetAvatarImageParamsSize) Valid() bool {
	switch e {
	case GetAvatarImageParamsSizeN100x100:
		return true
	case GetAvatarImageParamsSizeN128x128:
		return true
	case GetAvatarImageParamsSizeN256x256:
		return true
	case GetAvatarImageParamsSizeN300x300:
		return true
	case GetAvatarImageParamsSizeN512x512:
		return true
	case GetAvatarImageParamsSizeN64x64:
		return true
	case GetAvatarImageParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarImageParamsFormat.
const (
	GetAvatarImageParamsFormatJpeg GetAvatarImageParamsFormat = "jpeg"
	GetAvatarImageParamsFormatPng  GetAvatarImageParamsFormat = "png"
	GetAvatarImageParamsFormatWebp GetAvatarImageParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetAvatarImageParamsFormat enum.
func (e GetAvatarImageParamsFormat) Valid() bool {
	switch e {
	case GetAvatarImageParamsFormatJpeg:
		return true
	case GetAvatarImageParamsFormatPng:
		return true
	case GetAvatarImageParamsFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsSize.
const (
	N100x100 GetUserAvatarParamsSize = "100x100"
	N128x128 GetUserAvatarParamsSize = "128x128"
	N256x256 GetUserAvatarParamsSize = "256x256"
	N300x300 GetUserAvatarParamsSize = "300x300"
	N512x512 GetUserAvatarParamsSize = "512x512"
	N64x64   GetUserAvatarParamsSize = "64x64"
	Original GetUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsSize enum.
func (e GetUserAvatarParamsSize) Valid() bool {
	switch e {
	case N100x100:
		return true
	case N128x128:
		return true
	case N256x256:
		return true
	case N300x300:
		return true
	case N512x512:
		return true
	case N64x64:
		return true
	case Original:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsFormat.
const (
	GetUserAvatarParamsFormatJpeg GetUserAvatarParamsFormat = "jpeg"
	GetUserAvatarParamsFormatPng  GetUserAvatarParamsFormat = "png"
	GetUserAvatarParamsFormatWebp GetUserAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsFormat enum.
func (e GetUserAvatarParamsFormat) Valid() bool {
	switch e {
	case GetUserAvatarParamsFormatJpeg:
		return true
	case GetUserAvatarParamsFormatPng:
		return true
	case GetUserAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// AvatarListItem defines model for AvatarListItem.
type AvatarListItem struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    string             `json:"status"`
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time `json:"created_at"`
	Dimensions struct {
		Height int `json:"height"`
		Width  int `json:"width"`
	} `json:"dimensions"`
	FileName   string             `json:"file_name"`
	Id         openapi_types.UUID `json:"id"`
	MimeType   string             `json:"mime_type"`
	Size       int64              `json:"size"`
	Thumbnails []ThumbnailInfo    `json:"thumbnails"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     string             `json:"user_id"`
}

// AvatarUploadResponse defines model for AvatarUploadResponse.
type AvatarUploadResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    string             `json:"status"`

	// Url Public or internal URL for the avatar resource
	Url    string `json:"url"`
	UserId string `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	Error   string `json:"error"`
	MaxSize int64  `json:"max_size"`
}

// HealthResponse Arbitrary key/value health statuses (shape may evolve)
type HealthResponse map[string]interface{}

// ThumbnailInfo defines model for ThumbnailInfo.
type ThumbnailInfo struct {
	// Format Image variant key as stored for this thumbnail (matches S3 / worker keys)
	Format ThumbnailInfoFormat `json:"format"`
	Size   string              `json:"size"`
	Url    string              `json:"url"`
}

// ThumbnailInfoFormat Image variant key as stored for this thumbnail (matches S3 / worker keys)
type ThumbnailInfoFormat string

// AvatarId defines model for AvatarId.
type AvatarId = openapi_types.UUID

// Format defines model for Format.
type Format string

// Size defines model for Size.
type Size string

// UserIdPath defines model for UserIdPath.
type UserIdPath = string

// XUserID defines model for XUserID.
type XUserID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = FileTooLargeError

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Image file (max 10MB; jpeg, png, or webp recommended)
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Authenticated or trusted user id (caller identity)
	XUserID XUserID `json:"X-User-ID"`
}

// DeleteAvatarByIdParams defines parameters for DeleteAvatarById.
type DeleteAvatarByIdParams struct {
	// XUserID Authenticated or trusted user id (caller identity)
	XUserID XUserID `json:"X-User-ID"`
}

// GetAvatarImageParams defines parameters for GetAvatarImage.
type GetAvatarImageParams struct {
	Size   *GetAvatarImageParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format *GetAvatarImageParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetAvatarImageParamsSize defines parameters for GetAvatarImage.
type GetAvatarImageParamsSize string

// GetAvatarImageParamsFormat defines parameters for GetAvatarImage.
type GetAvatarImageParamsFormat string

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Authenticated or trusted user id (caller identity)
	XUserID XUserID `json:"X-User-ID"`
}

// GetUserAvatarParams defines parameters for GetUserAvatar.
type GetUserAvatarParams struct {
	Size   *GetUserAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format *GetUserAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetUserAvatarParamsSize defines parameters for GetUserAvatar.
type GetUserAvatarParamsSize string

// GetUserAvatarParamsFormat defines parameters for GetUserAvatar.
type GetUserAvatarParamsFormat string

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody
