// Package httphandler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httphandler

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload an avatar
	// (POST /api/v1/avatars)
	UploadAvatar(ctx echo.Context, params UploadAvatarParams) error
	// Delete avatar by id
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatarById(ctx echo.Context, avatarId AvatarId, params DeleteAvatarByIdParams) error
	// Get avatar image bytes
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatarImage(ctx echo.Context, avatarId AvatarId, params GetAvatarImageParams) error
	// Get avatar metadata
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx echo.Context, avatarId AvatarId) error
	// Delete user's avatar
	// (DELETE /api/v1/users/{user_id}/avatar)
	DeleteUserAvatar(ctx echo.Context, userId UserIdPath, params DeleteUserAvatarParams) error
	// Get current avatar for user
	// (GET /api/v1/users/{user_id}/avatar)
	GetUserAvatar(ctx echo.Context, userId UserIdPath, params GetUserAvatarParams) error
	// List user's avatars
	// (GET /api/v1/users/{user_id}/avatars)
	ListUserAvatars(ctx echo.Context, userId UserIdPath) error
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UploadAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UploadAvatar(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadAvatar(ctx, params)
	return err
}

// DeleteAvatarById converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAvatarById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarByIdParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAvatarById(ctx, avatarId, params)
	return err
}

// GetAvatarImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarImageParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarImage(ctx, avatarId, params)
	return err
}

// GetAvatarMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarMetadata(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarMetadata(ctx, avatarId)
	return err
}

// DeleteUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAvatar(ctx, userId, params)
	return err
}

// GetUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserAvatar(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserAvatarParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserAvatar(ctx, userId, params)
	return err
}

// ListUserAvatars converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAvatars(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAvatars(ctx, userId)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/avatars", wrapper.UploadAvatar)
	router.DELETE(baseURL+"/api/v1/avatars/:avatar_id", wrapper.DeleteAvatarById)
	router.GET(baseURL+"/api/v1/avatars/:avatar_id", wrapper.GetAvatarImage)
	router.GET(baseURL+"/api/v1/avatars/:avatar_id/metadata", wrapper.GetAvatarMetadata)
	router.DELETE(baseURL+"/api/v1/users/:user_id/avatar", wrapper.DeleteUserAvatar)
	router.GET(baseURL+"/api/v1/users/:user_id/avatar", wrapper.GetUserAvatar)
	router.GET(baseURL+"/api/v1/users/:user_id/avatars", wrapper.ListUserAvatars)
	router.GET(baseURL+"/health", wrapper.GetHealth)

}
