package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"govatars/internal/models"
	"govatars/internal/usecase"
)

// AvatarRepository persists avatar metadata.
type AvatarRepository struct {
	pool *pgxpool.Pool
}

// NewAvatarRepository constructs a metadata repository.
func NewAvatarRepository(pool *pgxpool.Pool) *AvatarRepository {
	return &AvatarRepository{pool: pool}
}

// Insert creates a new avatar row (id is generated by the caller).
func (r *AvatarRepository) Insert(ctx context.Context, a *models.Avatar) error {
	var thumbs []byte
	if len(a.ThumbnailS3Keys) > 0 {
		var err error
		thumbs, err = json.Marshal(a.ThumbnailS3Keys)
		if err != nil {
			return err
		}
	}
	_, err := r.pool.Exec(ctx, `
		INSERT INTO avatars (
			id, user_id, file_name, mime_type, size_bytes, s3_key, thumbnail_s3_keys,
			processing_status
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
	`, a.ID, a.UserID, a.FileName, a.MimeType, a.SizeBytes, a.S3Key, thumbs,
		string(a.ProcessingStatus))
	return err
}

// DeleteHard removes a row (used when rolling back a failed publish).
func (r *AvatarRepository) DeleteHard(ctx context.Context, id uuid.UUID) error {
	tag, err := r.pool.Exec(ctx, `DELETE FROM avatars WHERE id = $1`, id)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return errors.New("postgres: no row to delete")
	}
	return nil
}

// GetByID returns a non-deleted avatar by id.
func (r *AvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	row := r.pool.QueryRow(ctx, `
		SELECT id, user_id, file_name, mime_type, size_bytes, width, height, s3_key, thumbnail_s3_keys,
		       processing_status, created_at, updated_at, deleted_at
		FROM avatars WHERE id = $1 AND deleted_at IS NULL
	`, id)
	a, err := scanAvatarRow(row)
	if err != nil {
		return nil, err
	}
	return a, nil
}

// GetByIDIncludingDeleted loads a row even if soft-deleted (worker / diagnostics).
func (r *AvatarRepository) GetByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (*models.Avatar, error) {
	row := r.pool.QueryRow(ctx, `
		SELECT id, user_id, file_name, mime_type, size_bytes, width, height, s3_key, thumbnail_s3_keys,
		       processing_status, created_at, updated_at, deleted_at
		FROM avatars WHERE id = $1
	`, id)
	return scanAvatarRow(row)
}

// ListByUser lists avatars for a user (non-deleted).
func (r *AvatarRepository) ListByUser(ctx context.Context, userID string) ([]models.Avatar, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, user_id, file_name, mime_type, size_bytes, width, height, s3_key, thumbnail_s3_keys,
		       processing_status, created_at, updated_at, deleted_at
		FROM avatars WHERE user_id = $1 AND deleted_at IS NULL
		ORDER BY created_at DESC
	`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var list []models.Avatar
	for rows.Next() {
		a, err := scanAvatarRow(rows)
		if err != nil {
			return nil, err
		}
		list = append(list, *a)
	}
	return list, rows.Err()
}

// GetLatestByUser returns the most recent avatar for a user.
func (r *AvatarRepository) GetLatestByUser(ctx context.Context, userID string) (*models.Avatar, error) {
	row := r.pool.QueryRow(ctx, `
		SELECT id, user_id, file_name, mime_type, size_bytes, width, height, s3_key, thumbnail_s3_keys,
		       processing_status, created_at, updated_at, deleted_at
		FROM avatars WHERE user_id = $1 AND deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT 1
	`, userID)
	return scanAvatarRow(row)
}

// SoftDelete marks an avatar deleted if it belongs to the user.
func (r *AvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID string) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE avatars
		SET deleted_at = now(), updated_at = now()
		WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
	`, id, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return usecase.ErrNotFound
	}
	return nil
}

// RestoreSoftDeleted clears deleted_at for a soft-deleted avatar owned by user.
func (r *AvatarRepository) RestoreSoftDeleted(ctx context.Context, id uuid.UUID, userID string) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE avatars
		SET deleted_at = NULL, updated_at = now()
		WHERE id = $1 AND user_id = $2 AND deleted_at IS NOT NULL
	`, id, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return usecase.ErrNotFound
	}
	return nil
}

// UpdateProcessingResult stores dimensions, thumbnail keys, and processing status after worker finishes.
func (r *AvatarRepository) UpdateProcessingResult(ctx context.Context, id uuid.UUID, width, height int,
	thumbs map[string]map[string]string, status models.ProcessingStatus,
) error {
	raw, err := json.Marshal(thumbs)
	if err != nil {
		return err
	}
	tag, err := r.pool.Exec(ctx, `
		UPDATE avatars
		SET width = $2, height = $3, thumbnail_s3_keys = $4, processing_status = $5, updated_at = now()
		WHERE id = $1 AND deleted_at IS NULL
	`, id, width, height, raw, string(status))
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return usecase.ErrNotFound
	}
	return nil
}

// SetProcessingStatus updates only processing_status (e.g. failed).
func (r *AvatarRepository) SetProcessingStatus(ctx context.Context, id uuid.UUID, status models.ProcessingStatus) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE avatars SET processing_status = $2, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
	`, id, string(status))
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return usecase.ErrNotFound
	}
	return nil
}

type rowScanner interface {
	Scan(dest ...any) error
}

func scanAvatarRow(row rowScanner) (*models.Avatar, error) {
	var (
		a         models.Avatar
		thumbsRaw []byte
		w, h      sql.NullInt32
		deletedAt sql.NullTime
		procSt    string
	)
	err := row.Scan(
		&a.ID, &a.UserID, &a.FileName, &a.MimeType, &a.SizeBytes, &w, &h, &a.S3Key, &thumbsRaw,
		&procSt, &a.CreatedAt, &a.UpdatedAt, &deletedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, usecase.ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	a.ProcessingStatus = models.ProcessingStatus(procSt)
	if w.Valid {
		v := int(w.Int32)
		a.Width = &v
	}
	if h.Valid {
		v := int(h.Int32)
		a.Height = &v
	}
	if len(thumbsRaw) > 0 {
		if err := json.Unmarshal(thumbsRaw, &a.ThumbnailS3Keys); err != nil {
			return nil, fmt.Errorf("avatar row thumbnails json: %w", err)
		}
	}
	if deletedAt.Valid {
		t := deletedAt.Time
		a.DeletedAt = &t
	}
	return &a, nil
}

var _ usecase.AvatarRepository = (*AvatarRepository)(nil)
